Update trufflehog.yaml

diff --git a/.github/workflows/trufflehog.yaml b/.github/workflows/trufflehog.yaml
--- a/.github/workflows/trufflehog.yaml
+++ b/.github/workflows/trufflehog.yaml
@@ -1,1 +1,40 @@
+name: CI
+on: push
+jobs:
+  trufflehog:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+    - name: Secret Scanning
+      run: |
+        echo $GITHUB_REPOSITORY
+        echo "Branch name is ${GITHUB_REF##*/}"
+        docker run --rm -e DOCKER_TTY=0 -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git https://github.com/$GITHUB_REPOSITORY --only-verified > trufflehog_result.txt  
+        # Add error handling if the previous command fails
+        if [ $? -ne 0 ]; then
+          echo "Trufflehog execution failed"
+          exit 1
+        fi
+    - name: Upload Trufflehog Result
+      uses: actions/upload-artifact@v2
+      with:
+        name: TruffleHog Results
+        path: trufflehog_result.txt
+    - name: Add output to Job Summary
+      run: cat trufflehog_result.txt >> $GITHUB_STEP_SUMMARY
+      shell: bash
+    - name: Check file size
+      run: |
+          FILE_PATH="trufflehog_result.txt"
+          FILE_SIZE=$(stat -c %s "$FILE_PATH")
 
+          if [ "$FILE_SIZE" -eq 0 ]; then
+            echo "Error: File size is zero!"
+            exit 0
+          else
+            echo "File size is not zero."
+            exit 1
+          fi
+          
+           
